// .vitepress/theme/components/LanguageToggle.vue
<script setup lang="ts">
import type { Locale } from "../content/siteCopy";

interface LanguageToggleProps {
  activeLocale: Locale;
  label: string;
  localeNames: Record<Locale, string>;
}

const props = defineProps<LanguageToggleProps>();
const emit = defineEmits<{
  change: [locale: Locale];
}>();

const locales: Locale[] = ["ja", "zh", "en"];
</script>

<template>
  <div class="locale-toggle" role="group" :aria-label="props.label">
    <button
      v-for="locale in locales"
      :key="locale"
      type="button"
      class="locale-toggle__button"
      :class="{ 'is-active': props.activeLocale === locale }"
      :aria-pressed="props.activeLocale === locale"
      @click="emit('change', locale)"
    >
      {{ props.localeNames[locale] }}
    </button>
  </div>
</template>

// src/components/LanguageToggle.tsx
import type { Locale } from "../content/siteCopy";

interface LanguageToggleProps {
  activeLocale: Locale;
  label: string;
  localeNames: Record<Locale, string>;
  onChange: (locale: Locale) => void;
}

export function LanguageToggle({
  activeLocale,
  label,
  localeNames,
  onChange,
}: LanguageToggleProps) {
  return (
    <div className="locale-toggle" role="group" aria-label={label}>
      {(["ja", "zh", "en"] as const).map((locale) => {
        const isActive = activeLocale === locale;

        return (
          <button
            key={locale}
            type="button"
            className={`locale-toggle__button${isActive ? " is-active" : ""}`}
            aria-pressed={isActive}
            onClick={() => onChange(locale)}
          >
            {localeNames[locale]}
          </button>
        );
      })}
    </div>
  );
}
